name: Update Site

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -U gdown

      - run: gdown 1AAuHOb-6zM8Sf13kynt4FanfZVy12gGP

      - run: unzip zappixelrush.github.io.zip

      - run: rm -f zappixelrush.github.io.zip

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git commit -m "Update site" || exit 0
          git push